baseURL = '/'
canonifyURLs = true
languageCode = 'en-us'
title = 'Lu Shen'
theme = ["barks", "hugo-embed-pdf-shortcode"]
enableInlineShortcodes = true

# Main menu
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 2
[[menu.main]]
    name = "Publications"
    url  = "/publications"
    weight = 2
[[menu.main]]
    name = "CV"
    url  = "/cv"
    weight = 3

#[[menu.main]]
#    name = "Teaching"
#    url  = "/teaching"
#    weight = 2



# Customization options
[params]

    [params.head]
        author = "Lu Shen"
        custom_css = "/custom.css"
        description = "Hi, I'm Lu Shen"
        keywords = ["astronomy", "galaxy evolution", "environmental effect", "clusters", "protoclusters"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
        title_font = "Cutive Mono"
        body_font = "Source Sans Pro"

    [params.colors]
        theme_color = "#333333"
        background_color = "#fcfbf9"
        text_color = "#333333"
        link_color = "#17442a"

    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:lushen@tamu.edu"
            weight = 1
        [params.social.github]
            name = "GitHub"
            class = "fab fa-github"
            url = "https://github.com/Luloisshen"
            weight = 2
        [params.social.orcid]
            name = "ORCID iD"
            class = "fab fa-orcid"
            url = "https://orcid.org/0000-0001-9495-7759"
            weight = 3
